services:
    nedra_rest.route_provider:
        class: Nedra\RestBundle\Routing\Provider\RouteCollectionProvider
        arguments: ["%nedrarest.config%"]
        autowire: true

    Nedra\RestBundle\Routing\ModularRouter:
        tags:
            - { name: router, priority: 50 }

    nedra_rest.registry:
        class: Nedra\RestBundle\Component\Registry
        public: false

    nedra_rest.default_resource_type:
        class: Nedra\RestBundle\Form\Type\DefaultResourceType
        arguments:
          - "@doctrine.orm.entity_manager"
        public: false
        tags: ['form.type']

    nedra_rest.request_form_factory:
        class: Nedra\RestBundle\Controller\RequestFormConfiguration
        arguments: ["@form.factory"]
        public: false

    Nedra\RestBundle\Controller\:
        resource: '../../Controller'

        calls:
            - method: "setEntityManager"
              arguments:
                - "@doctrine.orm.entity_manager"

            - method: "setRequestFormFactory"
              arguments:
                - "@nedra_rest.request_form_factory"

        public: true
        tags: ['controller.service_arguments']
