dist: precise

language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  

install:
  - composer require satooshi/php-coveralls:~0.6@stable

script:
  - composer install
  - vendor/bin/phpunit
  - vendor/bin/coveralls -v
