dist: precise

language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'


script:
  - composer install
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/coveralls -v --exclude-no-stmt