install:
   - composer require --no-update symfony/framework-bundle "${SYMFONY_VERSION}"

language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm

matrix:
  include:
    - php: 5.6
      env: deps=low
    - php: 7.0
      env: deps=low

env:
  global:
    - deps=no

install:
  - if [ "$deps" = "no" ]; then composer install; fi;
  - if [ "$deps" = "low" ]; then composer update --prefer-lowest; fi;

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/coveralls -v --exclude-no-stmt